version: 2

models:
  - name: env_facts_table
    description: "Fact table containing environmental data."
    # Define the columns of the fact table
    columns:
      - name: date
        tests:
          - unique
          - not_null
      - name: city
        tests:
          - unique
          - not_null
      # Add other columns as needed

  - name: city_dimension
    description: "Dimension table containing unique city names."
    # Define the columns of the city dimension table
    columns:
      - name: city
        tests:
          - unique
          - not_null

  - name: date_dimension
    description: "Dimension table containing unique dates."
    # Define the columns of the date dimension table
    columns:
      - name: date
        tests:
          - unique
          - not_null
      - name: year
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: day
        tests:
          - not_null

# Define relationships between the models
relationships:
  - description: "Relationship between env_facts_table and city_dimension"
    # Specify the columns involved in the relationship
    columns:
      - name: city
        # Define the source and target columns
        from: env_facts_table.city
        to: city_dimension.city

  - description: "Relationship between env_facts_table and date_dimension"
    columns:
      - name: date
        from: env_facts_table.date
        to: date_dimension.date
