your_profile_name:  # Replace with your profile name
  target: dev  # You can specify different targets (e.g., dev, prod)
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: data-management-2-421815  # Replace with your GCP project ID
      dataset: weather_quality_climate  # Replace with your BigQuery dataset name
      location: europe-west3  # Replace with the location of your dataset
      threads: 1  # Number of threads to use for concurrent queries (optional)
      timeout_seconds: 300  # Timeout for queries in seconds (optional)
      priority: interactive  # Query priority (optional, choose from interactive or batch)

